/**
 * src/data/kanji_master.csv  ->  src/data/kanji.generated.ts
 *
 * Baking the dataset into a TS module (rather than fetching CSV at runtime)
 * removes a network hop from boot and lets the forge's attribute tables be
 * type-checked against the real character list.
 *
 * Two things the source CSV needs fixed on the way through:
 *   1. 18 characters appear at two JLPT levels. The easier level wins — a
 *      kanji is taught once, at the point the learner first meets it.
 *   2. The `world` / `order` columns are corrupt for N3/N4 (negative worlds
 *      leave ~220 N3 kanji unreachable), so they are dropped here. Stage
 *      assignment lives in src/data/stages.ts instead.
 *
 *   node scripts/build_kanji_data.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const CSV = 'src/data/kanji_master.csv';
const OUT = 'src/data/kanji.generated.ts';

const LEVEL_RANK = { N5: 0, N4: 1, N3: 2 };

const raw = readFileSync(CSV, 'utf8').trim().split('\n');
const header = raw[0].split(',');
const idx = Object.fromEntries(header.map((h, i) => [h, i]));

const splitList = (s) =>
  (s ?? '')
    .split('|')
    .map((v) => v.trim())
    .filter((v) => v && v !== '-');

/** @type {Map<string, object>} keyed by character */
const byChar = new Map();

for (const line of raw.slice(1)) {
  const f = line.split(',');
  if (f.length !== header.length) {
    console.warn(`skipping malformed row: ${line.slice(0, 40)}…`);
    continue;
  }
  const char = f[idx.char];
  const level = f[idx.level];
  if (!(level in LEVEL_RANK)) {
    console.warn(`skipping unknown level ${level} for ${char}`);
    continue;
  }

  const record = {
    id: f[idx.id],
    char,
    level,
    on: splitList(f[idx.readings_on]),
    kun: splitList(f[idx.readings_kun]),
    meanings: splitList(f[idx.meanings]),
    strokes: Number(f[idx.strokes]) || 1,
    tags: splitList(f[idx.tags]),
    exampleSentence: f[idx.example_sentence] || undefined,
    exampleReading: f[idx.example_reading] || undefined,
  };

  const existing = byChar.get(char);
  if (!existing || LEVEL_RANK[level] < LEVEL_RANK[existing.level]) {
    byChar.set(char, record);
  }
}

// Stable order: level first, then stroke count, then the source order. Simple
// characters come first inside a level, which is also the order they are
// taught in.
const sourceOrder = new Map([...byChar.keys()].map((c, i) => [c, i]));
const all = [...byChar.values()].sort(
  (a, b) =>
    LEVEL_RANK[a.level] - LEVEL_RANK[b.level] ||
    a.strokes - b.strokes ||
    sourceOrder.get(a.char) - sourceOrder.get(b.char),
);

// Ids must be unique — they key the learner's progress record.
const seenIds = new Set();
for (const k of all) {
  if (seenIds.has(k.id)) {
    const fixed = `${k.id}_${k.char.codePointAt(0).toString(16)}`;
    console.warn(`duplicate id ${k.id} -> ${fixed}`);
    k.id = fixed;
  }
  seenIds.add(k.id);
}

const counts = all.reduce((acc, k) => ({ ...acc, [k.level]: (acc[k.level] ?? 0) + 1 }), {});

const body = all
  .map((k) => {
    const parts = [
      `id:${JSON.stringify(k.id)}`,
      `char:${JSON.stringify(k.char)}`,
      `level:${JSON.stringify(k.level)}`,
      `on:${JSON.stringify(k.on)}`,
      `kun:${JSON.stringify(k.kun)}`,
      `meanings:${JSON.stringify(k.meanings)}`,
      `strokes:${k.strokes}`,
      `tags:${JSON.stringify(k.tags)}`,
    ];
    if (k.exampleSentence) parts.push(`exampleSentence:${JSON.stringify(k.exampleSentence)}`);
    if (k.exampleReading) parts.push(`exampleReading:${JSON.stringify(k.exampleReading)}`);
    return `  { ${parts.join(', ')} },`;
  })
  .join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/build_kanji_data.mjs — do not edit by hand.
// Source: src/data/kanji_master.csv
// ${all.length} kanji (N5:${counts.N5} / N4:${counts.N4} / N3:${counts.N3})
import type { KanjiData } from '../types/kanji';

export const ALL_KANJI: readonly KanjiData[] = [
${body}
];
`,
);

console.log(`wrote ${OUT}: ${all.length} kanji (N5:${counts.N5} / N4:${counts.N4} / N3:${counts.N3})`);
