/**
 * Collect every Game Icons name referenced by the data files and write a
 * narrow import module.
 *
 * `import * as Gi from 'react-icons/gi'` pulls all 4,040 components into the
 * bundle (7.5 MB). Importing only the names in use keeps it to what the game
 * can actually show. Run this after adding an icon to a weapon pool or a
 * stage's opponent.
 *
 *   node scripts/build_icon_registry.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCES = ['src/lib/forge/weapon.ts', 'src/data/stages.ts', 'src/data/scripts/tutorial.ts'];
const OUT = 'src/lib/gameIcons.ts';

const names = new Set();
for (const file of SOURCES) {
  for (const m of readFileSync(file, 'utf8').matchAll(/'(Gi[A-Za-z0-9]+)'/g)) names.add(m[1]);
}
const sorted = [...names].sort();
const list = sorted.map((n) => `  ${n},`).join('\n');

writeFileSync(
  OUT,
  `import type { ComponentType } from 'react';
import {
${list}
} from 'react-icons/gi';

/**
 * The icons the game actually uses, imported by name.
 *
 * react-icons/gi has 4,040 components. A wildcard import pulls in all of
 * them — it took the bundle to 7.5 MB — so every icon the game can show is
 * listed here and looked up through this map instead.
 *
 * GENERATED by scripts/build_icon_registry.mjs — do not edit by hand.
 */
export type IconComponent = ComponentType<{ size?: number; className?: string }>;

export const GAME_ICONS: Record<string, IconComponent> = {
${list}
};

export const getIcon = (name: string): IconComponent | undefined => GAME_ICONS[name];
`,
);

console.log(`wrote ${OUT} with ${sorted.length} icons`);
