/**
 * Build the compound-word (熟語) table the forge rewards.
 *
 * Source: EDICT2 from the Electronic Dictionary Research & Development Group
 * (http://ftp.edrdg.org/pub/Nihongo/edict2.gz), CC BY-SA 4.0. The file is not
 * committed; fetch it first:
 *
 *   curl -sSL -o /tmp/edict2.gz http://ftp.edrdg.org/pub/Nihongo/edict2.gz
 *   gunzip -f /tmp/edict2.gz
 *   node scripts/build_compounds.mjs /tmp/edict2
 *
 * Output: src/data/compounds.generated.ts — every 2- and 3-kanji word that can
 * be written using only the 618 kanji the game teaches, with its reading and a
 * short English gloss. This is what turns "combine two kanji" from a lookup
 * table someone had to invent into something the language already says.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2] ?? '/tmp/edict2';
const OUT = 'src/data/compounds.generated.ts';

// Read the character set straight out of the generated module rather than
// importing it, so this script stays runnable by plain node.
const generated = readFileSync('src/data/kanji.generated.ts', 'utf8');
const LEVEL = new Map(
  [...generated.matchAll(/char:"(.)", level:"(N[345])"/g)].map((m) => [m[1], m[2]]),
);
if (LEVEL.size === 0) {
  throw new Error('no kanji found in src/data/kanji.generated.ts — run build_kanji_data.mjs first');
}
const OWNED = new Set(LEVEL.keys());
const KANJI_ONLY = /^[一-龯]{2,3}$/;

// EDICT tags that mark an entry we should not put in front of a learner or
// that is not a plain noun-ish word.
const REJECT_TAGS = /\((?:vulg|derog|sl|obs|obsc|arch|rare|X|sK|iK|ok|ik|oK)\)/;
// Parts of speech worth keeping: nouns and noun-like words make weapon names.
const KEEP_POS = /\((?:[^)]*\b(?:n|n-adv|n-t|adj-no|adj-na|vs)\b[^)]*)\)/;

const lines = readFileSync(src, 'utf8').split('\n');

/** @type {Map<string, {word:string, reading:string, gloss:string, priority:boolean}>} */
const found = new Map();

for (const line of lines) {
  if (!line || line.startsWith('　')) continue;

  // 表記1;表記2 [よみ] /(pos) gloss/gloss/
  const m = line.match(/^([^\s[]+)\s+(?:\[([^\]]+)\]\s+)?\/(.*)\/?$/);
  if (!m) continue;
  const [, headwords, readingField, body] = m;

  if (REJECT_TAGS.test(body)) continue;
  if (!KEEP_POS.test(body)) continue;

  // (P) marks a high-frequency entry — these are the words worth rewarding.
  const priority = /\/\(P\)\//.test(line) || body.includes('(P)');

  const word = headwords.split(';')[0].replace(/\([^)]*\)/g, '');
  if (!KANJI_ONLY.test(word)) continue;
  if (![...word].every((c) => OWNED.has(c))) continue;

  const reading = (readingField ?? '').split(';')[0].replace(/\([^)]*\)/g, '').trim();
  if (!reading) continue;

  // First gloss only, trimmed of EDICT's bracketed metadata.
  const gloss = body
    .split('/')
    .map((g) => g.replace(/\([^)]*\)/g, '').trim())
    .filter((g) => g && !/^[A-Z]{1,4}$/.test(g))[0];
  if (!gloss || gloss.length > 40) continue;

  const existing = found.get(word);
  if (!existing || (priority && !existing.priority)) {
    found.set(word, { word, reading, gloss, priority });
  }
}

// Order: shortest first, then priority words, then alphabetical by reading —
// deterministic so the generated file does not churn between runs.
const all = [...found.values()].sort(
  (a, b) =>
    a.word.length - b.word.length ||
    Number(b.priority) - Number(a.priority) ||
    a.word.localeCompare(b.word, 'ja'),
);

/** The hardest level among a word's characters — the word's own level. */
const levelOf = (word) => {
  const ranks = [...word].map((c) => ({ N5: 0, N4: 1, N3: 2 })[LEVEL.get(c)] ?? 2);
  return ['N5', 'N4', 'N3'][Math.max(...ranks)];
};

// Only EDICT's high-frequency entries. The full set is 20k words deep and
// mostly words a learner at this level will never meet; rewarding 愛寒 the
// same as 火山 would teach the wrong thing, and the table has to ship to a
// phone.
const rows = all.filter((w) => w.priority).map((w) => ({ ...w, level: levelOf(w.word) }));
const two = rows.filter((r) => r.word.length === 2).length;
const three = rows.length - two;
const byLevel = rows.reduce((a, r) => ({ ...a, [r.level]: (a[r.level] ?? 0) + 1 }), {});

// Packed one word per line as word|reading|gloss|level, parsed once on first
// use. Object literals for the same data cost roughly three times as much.
const packed = rows.map((r) => `${r.word}|${r.reading}|${r.gloss.replace(/\|/g, '/')}|${r.level}`).join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/build_compounds.mjs — do not edit by hand.
// Source: EDICT2 (Electronic Dictionary Research & Development Group), CC BY-SA 4.0.
// High-frequency compounds writable with the game's 618 kanji:
// ${rows.length} words (${two} two-character, ${three} three-character)
// N5:${byLevel.N5 ?? 0} / N4:${byLevel.N4 ?? 0} / N3:${byLevel.N3 ?? 0}
import type { Compound } from '../types/forge';
import type { JlptLevel } from '../types/kanji';

/** word|reading|gloss|level, one per line. */
const PACKED = ${JSON.stringify(packed)};

let cache: readonly Compound[] | null = null;

/** The compound table, parsed on first use. */
export const getCompounds = (): readonly Compound[] => {
  if (cache) return cache;
  cache = PACKED.split('\\n').map((line) => {
    const [word, reading, gloss, level] = line.split('|');
    return { word, reading, gloss, level: level as JlptLevel, common: true };
  });
  return cache;
};
`,
);

console.log(
  `wrote ${OUT}: ${rows.length} high-frequency compounds (${two} 2-char, ${three} 3-char) — N5:${byLevel.N5 ?? 0} N4:${byLevel.N4 ?? 0} N3:${byLevel.N3 ?? 0}`,
);
