/**
 * Pre-render the picture book's layers to bitmaps.
 *
 * Every layer is an SVG with the torn-paper filter (four noise passes,
 * displacement, blur). WebKit — every browser on iPhone and iPad — ran that
 * filter at full screen size for each of a scene's ~10 layers, and again
 * whenever memory ran short and it dropped the result; on an iPad that is
 * millions of filtered pixels per layer. The result was lag and flicker
 * whenever anything on screen changed (2026-09-26, iPhone SE2 and M3 iPad).
 * Rendered once here, a layer is a plain image the phone only has to copy.
 *
 *   npx vite-node scripts/render_scenes.ts
 *   (CHROMIUM=/path/to/chrome to pick the browser)
 *
 * Output: public/img/scenes/<layerId>.webp and
 * src/features/picturebook/rendered.generated.ts (the ids that exist).
 * PictureBook falls back to the SVG for any layer not listed, so a scene
 * edited without re-running this still works — just slower on iPhone.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { chromium } from 'playwright';
import sharp from 'sharp';
import { SCENES } from '../src/features/picturebook/scenes';
import { PAGE_H, PAGE_W, toDataUrl } from '../src/features/picturebook/paper';
import { layerId } from '../src/features/picturebook/layerId';

/** 1.5× the page: sharp enough on a phone, and small enough to keep in memory. */
const SCALE = 1.5;
const OUT = 'public/img/scenes';

const svgs = new Map<string, string>();
for (const scene of Object.values(SCENES)) {
  for (const layer of scene.layers) svgs.set(layerId(layer.svg), layer.svg);
  for (const fx of Object.values(scene.fx)) for (const layer of fx) svgs.set(layerId(layer.svg), layer.svg);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const browser = await chromium.launch(process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {});
const page = await browser.newPage({ viewport: { width: PAGE_W, height: PAGE_H }, deviceScaleFactor: SCALE });
let bytes = 0;
for (const [id, svg] of svgs) {
  await page.setContent(
    `<html><body style="margin:0;background:transparent"><img id="l" src="${toDataUrl(svg)}" width="${PAGE_W}" height="${PAGE_H}" style="display:block"></body></html>`,
  );
  await page.waitForFunction(() => (document.getElementById('l') as HTMLImageElement).complete);
  const png = await page.screenshot({ omitBackground: true, clip: { x: 0, y: 0, width: PAGE_W, height: PAGE_H } });
  const webp = await sharp(png).webp({ quality: 82, alphaQuality: 90, effort: 5 }).toBuffer();
  writeFileSync(`${OUT}/${id}.webp`, webp);
  bytes += webp.length;
}
await browser.close();

const ids = readdirSync(OUT)
  .map((f) => f.replace(/\.webp$/, ''))
  .sort();
writeFileSync(
  'src/features/picturebook/rendered.generated.ts',
  `// GENERATED by scripts/render_scenes.ts — do not edit by hand.\n` +
    `// Picture-book layers that have a pre-rendered bitmap in public/img/scenes/.\n` +
    `export const RENDERED = new Set<string>(${JSON.stringify(ids)});\n`,
);
console.log(`rendered ${ids.length} layers, ${(bytes / 1024 / 1024).toFixed(1)} MB`);
